server:
  port: 4000
  forward-headers-strategy: framework
spring:
  main:
    allow-circular-references: true
  cache:
    type: redis
  redis:
    host: redis-12579.c85.us-east-1-2.ec2.cloud.redislabs.com
    port: 12579
    password: AfymxFNhu3wM9K4ObBib24M9OFwdHxj3
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
app:
  urlApi: https://lexicala1.p.rapidapi.com/search
  host: lexicala1.p.rapidapi.com
  key: 1c4317a744mshd65440aeaef3d67p1f8fb0jsn36ff2d050c0e

