version: '3'
services:
  mongodb:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
  backend:
    build:
      context: ./backend/TP-TACS
      dockerfile: Dockerfile
    image: backend 
    ports:
      - '4000:4000'
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    command: npm start