version: '3'
services:       
  backend:
    build:
      context: ./backend/TP-TACS
      dockerfile: Dockerfile
    image: backend 
    ports:
      - '4000:4000'
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    command: npm start
