version: '3'
services:
  backend:
    build:
      context: ./backend/TP-TACS
      dockerfile: Dockerfile
    image: backend 
    ports:
      - '8080:8080'
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - backend
    command: npm start